const stickersDataList = [
    {
        title:"tomAndJerry",
        id:1,
        tabImageUri:require("../assets/images/Stickers/thumbnail/avengers.png"),
        isPremiumNeeded:false,
        stickers:[
            {id:1,fileUri:require("../assets/images/Stickers/marvel/sticker_1.png")},
            {id:2,fileUri:require("../assets/images/Stickers/marvel/sticker_2.png")},
            {id:3,fileUri:require("../assets/images/Stickers/marvel/sticker_3.png")},
            {id:4,fileUri:require("../assets/images/Stickers/marvel/sticker_4.png")},
            {id:5,fileUri:require("../assets/images/Stickers/marvel/sticker_5.png")},
            {id:6,fileUri:require("../assets/images/Stickers/marvel/sticker_6.png")},
            {id:7,fileUri:require("../assets/images/Stickers/marvel/sticker_7.png")},
            {id:8,fileUri:require("../assets/images/Stickers/marvel/sticker_8.png")},
            {id:9,fileUri:require("../assets/images/Stickers/marvel/sticker_9.png")},
            {id:10,fileUri:require("../assets/images/Stickers/marvel/sticker_10.png")},
            {id:11,fileUri:require("../assets/images/Stickers/marvel/sticker_11.png")},
            {id:12,fileUri:require("../assets/images/Stickers/marvel/sticker_12.png")},
            {id:13,fileUri:require("../assets/images/Stickers/marvel/sticker_13.png")},
            {id:14,fileUri:require("../assets/images/Stickers/marvel/sticker_14.png")},
            {id:15,fileUri:require("../assets/images/Stickers/marvel/sticker_15.png")},
        ]
    },
    {
        title:"doraemon",
        id:2,
        tabImageUri:require("../assets/images/Stickers/thumbnail/doraemon.png"),
        isPremiumNeeded:true,
        stickers:[
            {id:1,fileUri:require("../assets/images/Stickers/doramon/sticker_1.png"),isPremiumNeeded:true,},
            {id:2,fileUri:require("../assets/images/Stickers/doramon/sticker_2.png"),isPremiumNeeded:true,},
            {id:3,fileUri:require("../assets/images/Stickers/doramon/sticker_3.png"),isPremiumNeeded:true,},
            {id:4,fileUri:require("../assets/images/Stickers/doramon/sticker_4.png"),isPremiumNeeded:true,},
            {id:5,fileUri:require("../assets/images/Stickers/doramon/sticker_5.png"),isPremiumNeeded:true,},
            {id:6,fileUri:require("../assets/images/Stickers/doramon/sticker_6.png"),isPremiumNeeded:true,},
            {id:7,fileUri:require("../assets/images/Stickers/doramon/sticker_7.png"),isPremiumNeeded:true,},
            {id:8,fileUri:require("../assets/images/Stickers/doramon/sticker_8.png"),isPremiumNeeded:true,},
            {id:9,fileUri:require("../assets/images/Stickers/doramon/sticker_9.png"),isPremiumNeeded:true,},
            {id:10,fileUri:require("../assets/images/Stickers/doramon/sticker_10.png"),isPremiumNeeded:true,},
            {id:11,fileUri:require("../assets/images/Stickers/doramon/sticker_11.png"),isPremiumNeeded:true,},
            {id:12,fileUri:require("../assets/images/Stickers/doramon/sticker_12.png"),isPremiumNeeded:true,},
            {id:13,fileUri:require("../assets/images/Stickers/doramon/sticker_13.png"),isPremiumNeeded:true,},
            {id:14,fileUri:require("../assets/images/Stickers/doramon/sticker_14.png"),isPremiumNeeded:true,},
            {id:15,fileUri:require("../assets/images/Stickers/doramon/sticker_15.png"),isPremiumNeeded:true,},
        ]
    },
];

export {stickersDataList}