const ThemesDataList = [
  {
    name: "theme_1",
    image: require("./../assets/images/themes/theme1.jpg"),
    topBarBg: "#E5DBFB",
    topBarTitleColor: "#000000",
    topBarIconColor: "#663EB4",
    bottonBarBg: "#E5DBFB",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#663EB4",
    addDiaryIconColor: "#FFFFFF",
    buttonBg: "#BFA4F4",
    buttonTextColor: "#000000",
    bodyBgColor: "#F2EDFD",
    calendarCurrentBG: "#8673AB",
    calendarSelectedDayBG: "#D9C8F8",
  },
  {
    name: "theme_2",
    image: require("./../assets/images/themes/theme2.jpg"),
    topBarBg: "#023859",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#276A93",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#478AAD",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#6593A6",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#C5D7D9",
    calendarCurrentBG: "#023859",
    calendarSelectedDayBG: "#276A93",
  },
  {
    name: "theme_3",
    image: require("./../assets/images/themes/theme3.jpg"),
    topBarBg: "#F48A31",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#E3823F",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#F48A31",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#F48A31",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#FEBD59",
    calendarCurrentBG: "#E3823F",
    calendarSelectedDayBG: "#F48A31",
  },
  {
    name: "theme_4",
    image: require("./../assets/images/themes/theme4.jpg"),
    topBarBg: "#4465A6",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#BFB2AA",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#AC8C74",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#BFB2AA",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#F2F2F0",
    calendarCurrentBG: "#4465A6",
    calendarSelectedDayBG: "#BFB2AA",
  },
  {
    name: "theme_5",
    image: require("./../assets/images/themes/theme5.jpg"),
    topBarBg: "#BF895A",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#F2D194",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#BF895A",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#BF895A",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#F2E6D0",
    calendarCurrentBG: "#BF895A",
    calendarSelectedDayBG: "#DCBCA0",
  },
  {
    name: "theme_6",
    image: require("./../assets/images/themes/theme6.jpg"),
    topBarBg: "#60A672",
    topBarTitleColor: "#FFFFFF",
    topBarIconColor: "#FFFFFF",
    bottonBarBg: "#69BFAF",
    bottomBarIconColor: "#FFFFFF",
    addDiaryBtnBg: "#F2DC6B",
    addDiaryIconColor: "#000000",
    buttonBg: "#80C3AD",
    buttonTextColor: "#000000",
    bodyBgColor: "#F2D5D5",
    calendarCurrentBG: "#60A672",
    calendarSelectedDayBG: "#69BFAF",
  },
  {
    name: "theme_7",
    image: require("./../assets/images/themes/theme7.jpg"),
    topBarBg: "#F1AEF2",
    topBarTitleColor: "#000000",
    topBarIconColor: "#000000",
    bottonBarBg: "#3B1273",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#75728C",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#F1AEF2",
    buttonTextColor: "#000000",
    bodyBgColor: "#D8BDF2",
    calendarCurrentBG: "#3B1273",
    calendarSelectedDayBG: "#F1AEF2",
  },
  {
    name: "theme_8",
    image: require("./../assets/images/themes/theme8.jpg"),
    topBarBg: "#3E848C",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#A3D9CF",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#F2E96B",
    addDiaryIconColor: "#000000",
    buttonBg: "#3E848C",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#D5F2EF",
    calendarCurrentBG: "#3E848C",
    calendarSelectedDayBG: "#A3D9CF",
  },
  {
    name: "theme_9",
    image: require("./../assets/images/themes/theme9.png"),
    topBarBg: "#238C82",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#238C82",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#5FBEB3",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#F2A950",
    buttonTextColor: "#000000",
    bodyBgColor: "#FBEDA9",
    calendarCurrentBG: "#238C82",
    calendarSelectedDayBG: "#5FBEB3",
  },
  {
    name: "theme_10",
    image: require("./../assets/images/themes/theme10.png"),
    topBarBg: "#D95B7D",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#D95B7D",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#4189A6",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#F27E88",
    buttonTextColor: "#000000",
    bodyBgColor: "#F2E8E4",
    calendarCurrentBG: "#238C82",
    calendarSelectedDayBG: "#5FBEB3",
  },
  {
    name: "theme_11",
    image: require("./../assets/images/themes/theme11.png"),
    topBarBg: "#162840",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#2B3D55",
    bottomBarIconColor: "#ffffff",
    addDiaryBtnBg: "#663EB4",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#2B3D55",
    buttonTextColor: "#ffffff",
    bodyBgColor: "#F2EEE9",
    calendarCurrentBG: "#2B3D55",
    calendarSelectedDayBG: "#8B8F96",
  },
  {
    name: "theme_13",
    image: require("./../assets/images/themes/theme13.png"),
    topBarBg: "#077373",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#68B0A2",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#077373",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#68B0A2",
    buttonTextColor: "#000000",
    bodyBgColor: "#F2E6D0",
    calendarCurrentBG: "#077373",
    calendarSelectedDayBG: "#68B0A2",
  },
  {
    name: "theme_12",
    image: require("./../assets/images/themes/theme12.png"),
    topBarBg: "#193B59",
    topBarTitleColor: "#ffffff",
    topBarIconColor: "#ffffff",
    bottonBarBg: "#DAA78A",
    bottomBarIconColor: "#663EB4",
    addDiaryBtnBg: "#1A395B",
    addDiaryIconColor: "#ffffff",
    buttonBg: "#D8956E",
    buttonTextColor: "#000000",
    bodyBgColor: "#F2D9BB",
    calendarCurrentBG: "#1A395B",
    calendarSelectedDayBG: "#8B8F96",
  },
  
];

export default ThemesDataList;
